name: Make All

on:
  workflow_dispatch:
  push:
    branches:
      - pinglin/update-ga-scripts

jobs:
  make-all-ubuntu:
    runs-on: ubuntu-latest
    steps:
      # mono occupies port 8084 which conflicts with mgmt-backend
      - name: Stop mono service
        run: |
          sudo kill -9 `sudo lsof -t -i:8084`
          sudo lsof -i -P -n | grep LISTEN

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: "true"
          remove-dotnet: "true"
          build-mount-path: "/var/lib/docker/"

      - name: Restart docker
        run: sudo service docker restart

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: instill-ai/instill-core
          fetch-depth: 0 # fetch the commit with tag

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - name: Launch Instill Core (release)
        run: |
          make all BUILD=true EDITION=local-ce:test

      - name: List all docker containers
        run: |
          docker ps -a
          sleep 60

      - name: Probe to Instill Core services healthcheck endpoint
        run: |
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/core/v1beta/health/mgmt
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/vdp/v1beta/health/pipeline
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/model/v1beta/health/model

      - name: Tear down Instill Core (release)
        run: |
          make down

  make-all-macos:
    runs-on: [self-hosted, on-prem, mac-studio]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: instill-ai/instill-core
          fetch-depth: 0 # fetch the commit with tag

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - name: Tear down previous Instill Core (if any)
        run: |
          make down

      - name: Launch Instill Core (release)
        run: |
          make all BUILD=true EDITION=local-ce:test

      - name: List all docker containers
        run: |
          docker ps -a
          sleep 60

      - name: Probe to Instill Core services healthcheck endpoint
        run: |
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/core/v1beta/health/mgmt
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/vdp/v1beta/health/pipeline
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/model/v1beta/health/model

      - name: Tear down Instill Core
        run: |
          make down

  make-all-windows:
    runs-on: windows-latest
    steps:
      - name: Install Docker Buildx
        run: |
          curl.exe -LO https://github.com/docker/buildx/releases/download/v0.10.5/buildx-v0.10.5.windows-amd64.exe
          mkdir $env:USERPROFILE\.docker\cli-plugins
          move buildx-v0.10.5.windows-amd64.exe $env:USERPROFILE\.docker\cli-plugins\docker-buildx.exe

      - run: |
          docker version
          docker buildx version

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: instill-ai/instill-core
          fetch-depth: 0 # fetch the commit with tag

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - name: Set up WSL
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04

      - name: Verify WSL and Docker
        run: |
          wsl -l -v
          docker version

      - name: Configure Docker Desktop to Use WSL 2
        run: |
          wsl --shutdown
          wsl --set-version Ubuntu 2

      - name: Verify WSL and Docker
        run: |
          wsl -l -v
          docker version

      - name: Install Docker and build-essential in WSL
        shell: wsl-bash {0} # https://github.com/marketplace/actions/setup-wsl#default-shell
        run: |
          sudo apt install -y build-essential
          curl -sSL https://get.docker.com/ | sh
          sudo service docker start

      - name: Launch Instill Core (release)
        shell: wsl-bash {0} # https://github.com/marketplace/actions/setup-wsl#default-shell
        run: |
          echo "export DOCKER_HOST=tcp://localhost:2375" >> ~/.bashrc
          source ~/.bashrc
          make all BUILD=true EDITION=local-ce:test

      - name: List all docker containers
        run: |
          docker ps -a
          sleep 60

      - name: Probe to Instill Core services healthcheck endpoint
        run: |
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/core/v1beta/health/mgmt
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/vdp/v1beta/health/pipeline
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/model/v1beta/health/model

      - name: Tear down Instill Core
        run: |
          make down
